### ISSUE TITLE
It's not necessary to make a workdir.

### ISSUE THREAD

**Issue by stenote** [2players/official-site#1]
https://github.com/2players/official-site/blob/9ed4376c1c60ee337b8ecec1c1ceedb43749be92/Dockerfile#L3

You can remove this line, and Dockerfile also works

**Comment by m31271n** [comment]
Thanks you.

**Comment by stenote** [comment]
https://docs.docker.com/engine/reference/builder/#workdir

```
If the WORKDIR doesn’t exist, it will be created even if it’s not used in any subsequent Dockerfile instruction.
```
